from __future__ import annotations

import csv
import importlib
import json
import os
import re
import shutil
import sys
import tempfile
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from fastapi import UploadFile

from .config import get_settings
from .hugegraph_client import HugeGraphRestClient


@dataclass
class IncidentImportResult:
    incidents: int
    nodes_written: int
    edges_written: int
    logs: list[str]

    def model_dump(self) -> dict[str, Any]:
        return {
            "incidents": self.incidents,
            "nodes_written": self.nodes_written,
            "edges_written": self.edges_written,
            "logs": self.logs,
        }


class IncidentGraphIntegrator:
    """Map sliding-window root-cause outputs into the architecture KG.

    Supported inputs:
    - incident_details.json generated by v1-goat logfault.run_pipeline
    - a ZIP containing incident_details.json and optional incidents.csv/events.csv
    - a directory containing those result files
    """

    def __init__(self, db: HugeGraphRestClient | None = None) -> None:
        self.settings = get_settings()
        self.db = db or HugeGraphRestClient()
        self.logs: list[str] = []
        self.nodes_written = 0
        self.edges_written = 0

    def import_path(self, path: str | Path, source_name: str = "") -> IncidentImportResult:
        source = Path(path)
        cleanup: tempfile.TemporaryDirectory[str] | None = None
        try:
            if source.is_file() and source.suffix.lower() == ".zip":
                cleanup = tempfile.TemporaryDirectory(prefix="logsys-incident-")
                with zipfile.ZipFile(source) as zf:
                    zf.extractall(cleanup.name)
                root = Path(cleanup.name)
            elif source.is_dir():
                root = source
            else:
                root = source.parent

            details_file = self._find_first(root, "incident_details.json")
            incidents_csv = self._find_first(root, "incidents.csv")
            events_csv = self._find_first(root, "events.csv")

            details: list[dict[str, Any]] = []
            if details_file:
                data = json.loads(details_file.read_text(encoding="utf-8"))
                if isinstance(data, list):
                    details = [x for x in data if isinstance(x, dict)]
                elif isinstance(data, dict):
                    details = [data]
                self.logs.append(f"读取 incident_details.json: {details_file}，故障数={len(details)}")
            elif source.is_file() and source.suffix.lower() == ".json":
                data = json.loads(source.read_text(encoding="utf-8"))
                if isinstance(data, list):
                    details = [x for x in data if isinstance(x, dict)]
                elif isinstance(data, dict):
                    details = [data]
                self.logs.append(f"读取 JSON: {source}，故障数={len(details)}")

            if not details and incidents_csv:
                details = self._details_from_incidents_csv(incidents_csv)
                self.logs.append(f"从 incidents.csv 生成最小故障详情: {incidents_csv}，故障数={len(details)}")

            if not details and events_csv:
                details = self._details_from_events_csv(events_csv)
                self.logs.append(f"从 events.csv 生成最小故障详情: {events_csv}，故障数={len(details)}")

            if not details:
                raise ValueError("没有找到 incident_details.json / incidents.csv / events.csv，无法导入异常链路。")

            self._import_details(details, source_name or source.name)
            return IncidentImportResult(len(details), self.nodes_written, self.edges_written, self.logs)
        finally:
            if cleanup is not None:
                cleanup.cleanup()

    def _find_first(self, root: Path, filename: str) -> Path | None:
        if root.is_file() and root.name == filename:
            return root
        if not root.exists():
            return None
        for path in root.rglob(filename):
            if path.is_file():
                return path
        return None

    def _details_from_incidents_csv(self, path: Path) -> list[dict[str, Any]]:
        rows = self._read_csv(path)
        details: list[dict[str, Any]] = []
        for idx, row in enumerate(rows, start=1):
            incident_id = row.get("incident_id") or f"I{idx:05d}"
            details.append({
                "incident_id": incident_id,
                "detected_window_start": row.get("detected_window_start") or row.get("start") or "",
                "detected_window_end": row.get("detected_window_end") or row.get("end") or "",
                "fault_start": row.get("fault_start") or row.get("start") or "",
                "fault_end": row.get("fault_end") or row.get("end") or "",
                "primary_trace_id": row.get("primary_trace_id") or "",
                "root_service_candidate": row.get("root_service_candidate") or "",
                "root_cause_candidate": row.get("root_cause_candidate") or "",
                "root_error_timestamp": row.get("root_error_timestamp") or "",
                "services": self._json_list(row.get("services")),
                "trace_ids": self._json_list(row.get("trace_ids")),
                "timeline": [],
                "root_candidates": [],
                "upstream_effects": [],
            })
        return details

    def _details_from_events_csv(self, path: Path) -> list[dict[str, Any]]:
        rows = self._read_csv(path)
        errors = [r for r in rows if str(r.get("level", "")).upper() == "ERROR"]
        if not errors:
            return []
        root = errors[0]
        trace_id = str(root.get("trace_id") or "")
        timeline = [r for r in rows if trace_id and str(r.get("trace_id") or "") == trace_id] or errors[:50]
        return [{
            "incident_id": "I00001",
            "detected_window_start": root.get("timestamp") or "",
            "detected_window_end": root.get("timestamp") or "",
            "fault_start": timeline[0].get("timestamp") if timeline else root.get("timestamp") or "",
            "fault_end": timeline[-1].get("timestamp") if timeline else root.get("timestamp") or "",
            "primary_trace_id": trace_id,
            "root_service_candidate": root.get("service") or "",
            "root_cause_candidate": root.get("root_cause") or root.get("semantic_message") or root.get("message") or "",
            "root_error_timestamp": root.get("timestamp") or "",
            "services": sorted({str(r.get("service") or "") for r in timeline if r.get("service")}),
            "trace_ids": [trace_id] if trace_id else [],
            "timeline": timeline,
            "root_candidates": [root],
            "upstream_effects": [],
        }]

    def _read_csv(self, path: Path) -> list[dict[str, str]]:
        with path.open("r", encoding="utf-8-sig", newline="") as f:
            return list(csv.DictReader(f))

    def _json_list(self, value: Any) -> list[str]:
        if value is None:
            return []
        if isinstance(value, list):
            return [str(x) for x in value if str(x).strip()]
        text = str(value).strip()
        if not text:
            return []
        try:
            data = json.loads(text)
            if isinstance(data, list):
                return [str(x) for x in data if str(x).strip()]
        except Exception:
            pass
        return [x.strip() for x in re.split(r"[,，;；]", text) if x.strip()]

    def _import_details(self, details: list[dict[str, Any]], source_name: str) -> None:
        self.db.ensure_schema()
        for detail in details:
            self._import_one(detail, source_name)

    def _write_node(self, name: str, layer: str, kind: str, description: str = "", source_file: str = "", meta: dict[str, Any] | None = None) -> None:
        if not name:
            return
        self.db.upsert_node(name=name, layer=layer, kind=kind, description=description, source_file=source_file, meta=meta or {})
        self.nodes_written += 1

    def _write_edge(self, source: str, target: str, rel_type: str, description: str = "", meta: dict[str, Any] | None = None) -> None:
        if not source or not target or source == target:
            return
        self.db.add_edge_by_names(source, target, rel_type, description, meta or {})
        self.edges_written += 1

    def _import_one(self, detail: dict[str, Any], source_name: str) -> None:
        incident_id = str(detail.get("incident_id") or "I00000")
        incident_node = f"Incident:{incident_id}"
        root_service_raw = str(detail.get("root_service_candidate") or "")
        root_service = self._resolve_arch_service(root_service_raw)
        primary_trace = str(detail.get("primary_trace_id") or "")
        root_cause = str(detail.get("root_cause_candidate") or "未提取到明确底层异常")
        exception_name = self._exception_node_name(root_cause)

        self._write_node(
            incident_node,
            "异常分析层",
            "Incident",
            f"故障 {incident_id}：{root_service_raw or '未知服务'} / {root_cause[:180]}",
            source_name,
            {
                "detected_window_start": detail.get("detected_window_start"),
                "detected_window_end": detail.get("detected_window_end"),
                "fault_start": detail.get("fault_start"),
                "fault_end": detail.get("fault_end"),
                "root_error_timestamp": detail.get("root_error_timestamp"),
            },
        )
        if root_service:
            self._write_node(root_service, "业务服务层", "Service", "异常链路关联到的服务", source_name, {"raw_service": root_service_raw})
            self._write_edge(incident_node, root_service, "ROOT_SERVICE", "故障归因到该服务", {"raw_service": root_service_raw})
        if exception_name:
            self._write_node(exception_name, "异常分析层", "Exception", root_cause[:500], source_name, {"root_cause": root_cause})
            self._write_edge(incident_node, exception_name, "ROOT_CAUSE", "故障根因异常", {"root_cause": root_cause})
        if primary_trace:
            trace_node = f"Trace:{primary_trace}"
            self._write_node(trace_node, "异常分析层", "Trace", f"主 traceId：{primary_trace}", source_name, {})
            self._write_edge(incident_node, trace_node, "HAS_TRACE", "故障主链路 trace", {})
        else:
            trace_node = ""

        timeline = detail.get("timeline") or []
        if isinstance(timeline, list):
            timeline = timeline[: max(1, int(self.settings.incident_timeline_limit))]
        else:
            timeline = []
        prev_event_node = ""
        prev_service_node = ""
        for idx, event in enumerate(timeline, start=1):
            if not isinstance(event, dict):
                continue
            service_raw = str(event.get("service") or "")
            service_node = self._resolve_arch_service(service_raw)
            timestamp = str(event.get("timestamp") or "")
            level = str(event.get("level") or "")
            msg = str(event.get("root_cause") or event.get("message") or "")
            event_node = f"LogEvent:{incident_id}:{idx:03d}"
            self._write_node(
                event_node,
                "异常分析层",
                "LogEvent",
                f"{timestamp} [{level}] {service_raw}: {msg[:220]}",
                source_name,
                {
                    "timestamp": timestamp,
                    "level": level,
                    "service": service_raw,
                    "trace_id": event.get("trace_id"),
                    "logger": event.get("logger"),
                    "template_id": event.get("template_id"),
                    "source_file": event.get("source_file"),
                    "source_line": event.get("source_line"),
                    "message": event.get("message"),
                    "root_cause": event.get("root_cause"),
                },
            )
            self._write_edge(incident_node, event_node, "HAS_EVENT", "故障包含该日志事件", {"order": idx})
            if trace_node:
                self._write_edge(trace_node, event_node, "HAS_EVENT", "trace 下的日志事件", {"order": idx})
            if service_node:
                self._write_node(service_node, "业务服务层", "Service", "异常链路关联到的服务", source_name, {"raw_service": service_raw})
                self._write_edge(service_node, event_node, "EMITS", "服务产生该异常日志", {"order": idx})
                if prev_service_node and prev_service_node != service_node:
                    self._write_edge(prev_service_node, service_node, "ERROR_PROPAGATES_TO", "异常沿时间线传播到下一个服务", {"incident_id": incident_id})
                prev_service_node = service_node
            if prev_event_node:
                self._write_edge(prev_event_node, event_node, "PROPAGATES_TO", "异常链路中的后续日志", {"incident_id": incident_id})
            prev_event_node = event_node

        # Candidate nodes make the evidence auditable even when timeline was trimmed.
        for idx, candidate in enumerate((detail.get("root_candidates") or [])[:10], start=1):
            if not isinstance(candidate, dict):
                continue
            cand_service = self._resolve_arch_service(str(candidate.get("service") or ""))
            cand_node = f"RootCandidate:{incident_id}:{idx:02d}"
            cand_text = str(candidate.get("root_cause") or candidate.get("message") or "")
            self._write_node(cand_node, "异常分析层", "LogEvent", cand_text[:500], source_name, candidate)
            self._write_edge(incident_node, cand_node, "TRIGGERED_BY", "根因候选证据", {"rank": idx})
            if cand_service:
                self._write_edge(cand_service, cand_node, "EMITS", "候选根因服务产生该日志", {"rank": idx})

        self.logs.append(f"导入 {incident_id}: root_service={root_service_raw or '-'}, trace={primary_trace or '-'}, timeline_events={len(timeline)}")

    def _exception_node_name(self, root_cause: str) -> str:
        text = root_cause.strip() or "UnknownException"
        match = re.search(r"([A-Za-z_][\w.$]*(?:Exception|Error))", text)
        if match:
            return f"Exception:{match.group(1).split('.')[-1]}"
        return "Exception:" + re.sub(r"\s+", " ", text[:48])

    def _resolve_arch_service(self, service_name: str) -> str:
        service_name = service_name.strip()
        if not service_name:
            return ""
        vertices = self.db.list_vertices(limit=10000)
        normalized = self._norm_service(service_name)
        best = ""
        for v in vertices:
            props = v.get("properties", {}) or {}
            name = str(props.get(self.db.pk_name) or "")
            kind = str(props.get(self.db.pk_kind) or "")
            if not name:
                continue
            if name == service_name:
                return name
            if kind in {"Service", "API", "Component"} and self._norm_service(name) == normalized:
                return name
            if kind in {"Service", "API", "Component"} and normalized and normalized in self._norm_service(name):
                best = best or name
        return best or service_name

    def _norm_service(self, value: str) -> str:
        text = value.lower()
        text = re.sub(r"(?:service|server|svc|服务|应用|模块|系统)$", "", text)
        text = re.sub(r"[^a-z0-9\u4e00-\u9fa5]", "", text)
        return text


class LogFaultRunner:
    """Optional adapter for the v1-goat sliding-window algorithm package."""

    def __init__(self) -> None:
        self.settings = get_settings()

    async def analyze_upload(self, file: UploadFile, train_file: UploadFile | None = None) -> dict[str, Any]:
        temp = tempfile.TemporaryDirectory(prefix="logsys-logfault-")
        try:
            root = Path(temp.name)
            input_path = root / (file.filename or "logs.zip")
            input_path.write_bytes(await file.read())
            train_path: Path | None = None
            if train_file is not None:
                train_path = root / (train_file.filename or "train_logs.zip")
                train_path.write_bytes(await train_file.read())
            output_root = Path(self.settings.logfault_output_root)
            output_root.mkdir(parents=True, exist_ok=True)
            output_dir = output_root / f"run-{os.getpid()}-{input_path.stem}"
            summary = self._run_pipeline(input_path, output_dir, train_path)
            result = IncidentGraphIntegrator().import_path(output_dir, source_name=str(input_path.name))
            return {"summary": summary, "incident_import": result.model_dump(), "output_dir": str(output_dir)}
        finally:
            temp.cleanup()

    def _run_pipeline(self, input_path: Path, output_dir: Path, train_path: Path | None) -> dict[str, Any]:
        if self.settings.logfault_project_path:
            project = Path(self.settings.logfault_project_path).expanduser().resolve()
            if str(project) not in sys.path:
                sys.path.insert(0, str(project))
        try:
            module = importlib.import_module("logfault.pipeline")
        except Exception as exc:  # noqa: BLE001
            raise RuntimeError(
                "无法导入 logfault.pipeline。请把 v1-goat 仓库路径配置到 LOGFAULT_PROJECT_PATH，"
                "或先用该算法生成 incident_details.json 后走“导入异常链路”。"
            ) from exc
        config_path = self.settings.logfault_config_path or None
        run_pipeline = getattr(module, "run_pipeline")
        return run_pipeline(
            input_path=input_path,
            output_dir=output_dir,
            config_path=config_path,
            train_input=train_path,
        )
